Modules/Admin/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Route;


Route::group(['middleware' => ['auth:web'], 'prefix' => 'admin'], function () {

    Route::get('system-update', function () {

        \Illuminate\Support\Facades\Artisan::call('cache:clear');
        \Illuminate\Support\Facades\Artisan::call('view:clear');
        \Illuminate\Support\Facades\Artisan::call('route:clear');

        \Illuminate\Support\Facades\Artisan::call('storage:link');
        \Illuminate\Support\Facades\Artisan::call('config:cache');
        dd("Process Done");
    });


    //Dashboard
    Route::get('/dashboard', 'DashboardController@index')->name('admin.dashboard');

    // Role routes
    Route::get('roles/get-data', 'RoleController@getData')->name('admin.roles.get-data');
    Route::resource('roles', 'RoleController', resourceNames('admin.roles'));

    // Role routes
    Route::get('permissions/get-data', 'PermissionController@getData')->name('admin.permissions.get-data');
    Route::resource('permissions', 'PermissionController', resourceNames('admin.permissions'));

    // User routes
    Route::get('users/get-data', 'UserController@getData')->name('admin.users.get-data');
    Route::resource('users', 'UserController', resourceNames('admin.users'));


    // News Category
    Route::get('news-category/get-data', 'NewsCategoryController@getData')->name('admin.news-category.get-data');
    Route::post('news-category/{auid}/active', 'NewsCategoryController@active')->name('admin.news-category.active');
    Route::post('news-category/{auid}/inactive', 'NewsCategoryController@inactive')->name('admin.news-category.inactive');
    Route::resource('news-category', 'NewsCategoryController', resourceNames('admin.news-category'));

    Route::get('product/get-data', 'ProductController@getData')->name('admin.product.get-data');
    Route::post('product/{auid}/active', 'ProductController@active')->name('admin.product.active');
    Route::post('product/{auid}/inactive', 'ProductController@inactive')->name('admin.product.inactive');
    Route::post('delete-image', 'ProductController@deleteImage')->withoutMiddleware([\App\Http\Middleware\VerifyCsrfToken::class])->name('admin.product.delete_image');

    Route::resource('product', 'ProductController', resourceNames('admin.product'));
//    Route::get('product/create_product', 'ProductController@showCreate')->name('admin.product.create_product');

    // News
    Route::get('news/get-data', 'NewsController@getData')->name('admin.news.get-data');
    Route::post('news/{auid}/active', 'NewsController@active')->name('admin.news.active');
    Route::post('news/{auid}/inactive', 'NewsController@inactive')->name('admin.news.inactive');
    Route::resource('news', 'NewsController', resourceNames('admin.news'));

    // Q & A
    Route::post('faq/update-faq-main', 'FaqController@updateMainFaq')->name('admin.faq.update-faq-main');
    Route::post('faq/update-faq-sub', 'FaqController@updateSubFaq')->name('admin.faq.update-faq-sub');
    Route::resource('faq', 'FaqController', resourceNames('admin.faq'));

    //Inquiry Management Routes
    Route::get('inquiry-management/get-data', 'InquiryManagementController@getData')->name('admin.inquiry-management.get-data');
    Route::resource('inquiry-management', 'InquiryManagementController', resourceNames('admin.inquiry-management'));

    //Admin Contact Management
    Route::post('web-content/update-contactUs', 'ContactUsController@updateContactUs')->name('admin.web-content.update-contactUs');
    Route::resource('web-content', 'ContactUsController', resourceNames('admin.web-content'));
});

Modules/Admin/Resources/views/common/footer.blade.php
<!-- Footer -->
<div class="navbar navbar-expand-lg navbar-light">
    <div class="text-center d-lg-none w-100">
        <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse"
                data-target="#navbar-footer">
            <i class="icon-unfold mr-2"></i>
            Footer
        </button>
    </div>

    <div class="navbar-collapse collapse text-center justify-content-center" id="navbar-footer">
        <span class="navbar-text">
            &copy; 2022 <a href="{{ url('/') }}" target="_blank"> {{ config('app.name', 'Laravel') }} </a> by <a href="http://zincat.net" target="_blank">Zincat Technology</a>
        </span>
    </div>
</div>
<!-- /footer -->

Modules/Admin/Resources/views/common/header.blade.php
<!-- Main navbar -->
<div class="navbar navbar-expand-lg navbar-dark navbar-static">
    <div class="navbar-brand text-center text-lg-left">
        <a href="{{ url('/') }}" target="_blank" class="d-inline-block">
            <img src="{{ asset('template_assets/assets/images/logo/logo_white.webp') }}" class="d-none d-sm-block" alt="">
            <img src="{{ asset('template_assets/assets/images/logo/logo_white.webp') }}" class="d-sm-none" alt="">
        </a>
    </div>

    <div class="d-flex align-items-center">
        <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
            <i class="icon-transmission"></i>
        </button>
        <a type="button" class="m-w-unset navbar-nav-link text-white border-transparent sidebar-control sidebar-main-resize d-none d-lg-inline-flex">
            <i class="icon-transmission"></i>
        </a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbar-mobile">
            <i class="icon-paragraph-justify3"></i>
        </button>
    </div>

    <div class="collapse navbar-collapse order-2 order-lg-1" id="navbar-mobile">
        <span class="badge badge-success my-3 my-lg-0 ml-lg-3">Online</span>
    </div>

    <ul class="navbar-nav flex-row order-1 order-lg-2 flex-1 flex-lg-0 justify-content-end align-items-center">

        <li class="nav-item nav-item-dropdown-lg dropdown dropdown-user h-100">
            <a href="#"
               class="navbar-nav-link navbar-nav-link-toggler dropdown-toggle d-inline-flex align-items-center h-100"
               data-toggle="dropdown">
                <img src="{{ \Illuminate\Support\Facades\Auth::user()->profile_image ?? '' }}" class="rounded-pill mr-lg-2"
                     height="34" alt="">
                <span class="d-none d-lg-inline-block"> {{ \Illuminate\Support\Facades\Auth::user()->display_name  }}</span>
            </a>

            <div class="dropdown-menu dropdown-menu-right">
                <a href="{{ route('admin.logout') }}"
                   onclick="event.preventDefault(); document.getElementById('admin-logout-form').submit();" class="dropdown-item"><i class="icon-switch2"></i> Logout</a>
                <form id="admin-logout-form" action="{{ route('admin.logout') }}" method="get" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</div>
<!-- /main navbar -->

Modules/Admin/Resources/views/common/page-header.blade.php
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><i class="{{isset($icon)?$icon:"icon-quill4"}}"></i><span
                        class="ml-2 font-weight-semibold">{{ isset($title)?$title:'' }}</span></h4>
        </div>

        <div class="header-elements py-0 py-sm-0 py-md-2 py-lg-2 py-xl-2">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{route('admin.dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i>
                        Home</a>
                    <a class="breadcrumb-item active">{{ isset($title)?$title:'' }}</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page header -->

Modules/Admin/Resources/views/common/sidebar.blade.php
<!-- Main sidebar -->
<div class="sidebar sidebar-dark sidebar-main sidebar-expand-lg">

    <!-- Sidebar content -->
    <div class="sidebar-content">

        <!-- User menu -->
        <div class="sidebar-section sidebar-user my-1">
            <div class="sidebar-section-body pt-1 pr-1">
                <div class="mb-1 d-flex justify-content-end align-self-center">
                    <button type="button"
                            class="btn m-w-unset p-0 text-white border-transparent btn-icon btn-sm sidebar-mobile-main-toggle d-lg-none">
                        <i class="icon-cross2"></i>
                    </button>
                </div>
                <div class="media">
                    <a href="#" class="mr-3">
                        <img src="{{ \Illuminate\Support\Facades\Auth::user()->profile_image ?? '' }}"
                             class="rounded-circle" alt="">
                    </a>

                    <div class="media-body">
                        <div class="font-weight-semibold"> {{ \Illuminate\Support\Facades\Auth::user()->display_name  }}</div>
                        <div class="font-size-sm line-height-sm opacity-50">
                            {{ @(\Illuminate\Support\Facades\Auth::user()->roles->pluck('name')[0]) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /user menu -->


        <!-- Main navigation -->
        <div class="sidebar-section">
            <ul class="nav nav-sidebar" data-nav-type="accordion">

                <!-- Main -->
                <li class="nav-item-header">
                    <div class="text-uppercase font-size-xs line-height-xs">Main Menu</div>
                    <i class="icon-menu" title="Main"></i></li>
                <li class="nav-item">
                    <a href="{{ route('admin.dashboard') }}" class="nav-link {{ Request::is('admin/dashboard') ? 'active' : '' }}"><i class="icon-home4"></i> <span>Dashboard</span></a>
                </li>



                <li class="nav-item">
                    <a href="{{ route('admin.product.index') }}" class="nav-link"><i class="icon-color-sampler"></i> <span>Product Management</span></a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('admin.news-category.index') }}" class="nav-link"><i class="icon-color-sampler"></i> <span>News Category Management</span></a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('admin.news.index') }}" class="nav-link"><i class="icon-color-sampler"></i> <span>News Management</span></a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('admin.faq.index') }}" class="nav-link"><i class="icon-color-sampler"></i> <span>Q & A Management</span></a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('admin.inquiry-management.index') }}" class="nav-link"><i class="icon-color-sampler"></i> <span>Inquiry Management</span></a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('admin.web-content.index') }}" class="nav-link"><i class="icon-color-sampler"></i> <span>Contact Management</span></a>
                </li>




                {{--@php( $active = $activeR = false)

                <li class="nav-item nav-item-submenu  {{ $active ? 'nav-item-open' : '' }}">
                    <a href="javascript:void(0);" class="nav-link "><i class="icon-people"></i> <span>User Management</span></a>

                    <ul class="nav nav-group-sub {{ $active ? 'd-block' : '' }}">

                        @can('View Roles')
                            <li class="nav-item"><a class="nav-link {{ Request::is('admin/roles') ? 'active' : '' }}" href="{{ route('admin.roles.index') }}">Roles</a></li>
                        @endcan
                        @can('View Permissions')
                            <li class="nav-item"><a class="nav-link {{ Request::is('admin/permissions') ? 'active' : '' }}" href="{{ route('admin.permissions.index') }}">Permissions</a></li>
                        @endcan
                        @can('View Users')
                            <li class="nav-item"><a class="nav-link {{ Request::is('admin/users') ? 'active' : '' }}" href="{{ route('admin.users.index') }}">Users</a></li>
                        @endcan
                        @can('View Action Log')
                            <li class="nav-item"><a class="nav-link {{ Request::is('admin/action-log') ? 'active' : '' }}" href="{{ route('admin.permissions.index') }}">Action Logs</a></li>
                        @endcan

                    </ul>
                </li>--}}

            </ul>
        </div>
        <!-- /main navigation -->

    </div>
    <!-- /sidebar content -->

</div>
<!-- /main sidebar -->